// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizzéria.Models;

#nullable disable

namespace Pizzéria.Migrations
{
    [DbContext(typeof(PizzaEhodDB))]
    partial class PizzaEhodDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Pizzéria.Models.PizzaEhod", b =>
                {
                    b.Property<int>("IdEhod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionEhod")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEhod")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEhod");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
